/*
 * CyberArk PKIaaS API
 *
 * API for CyberArk's Public-Key Infrastructure (PKI)-as-a-Service
 *
 * API version: 1.0.2
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body4 struct {

	Certificate string `json:"certificate,omitempty"`
}
