/*
 * CyberArk Identity Service API
 *
 * API for CyberArk's Identity Service
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body6 struct {

	Certificate string `json:"certificate,omitempty"`
}
