/*
 * CyberArk Identity as a Service API
 *
 * API for CyberArk's Identity as a Service (IDaaS)
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	Certificate string `json:"certificate,omitempty"`

	PrivateKey string `json:"privateKey,omitempty"`

	CaCertificate string `json:"caCertificate,omitempty"`

	SerialNumber string `json:"serialNumber,omitempty"`

	LeaseDuration string `json:"leaseDuration,omitempty"`
}
