/*
 * CyberArk PKIaaS API
 *
 * API for CyberArk's Public-Key Infrastructure (PKI)-as-a-Service
 *
 * API version: 1.0.2
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TemplateRequest struct {

	TemplateName string `json:"templateName"`

	KeyAlgorithm string `json:"keyAlgorithm"`

	KeyBits string `json:"keyBits"`

	TimeToLive string `json:"timeToLive"`

	Organization string `json:"organization"`

	OrganizationalUnit string `json:"organizationalUnit,omitempty"`

	Country string `json:"country"`

	Locality string `json:"locality"`

	Province string `json:"province,omitempty"`

	StreetAddress string `json:"streetAddress,omitempty"`

	PostalCode string `json:"postalCode,omitempty"`

	AltNames []string `json:"altNames,omitempty"`

	KeyUsage []string `json:"keyUsage"`

	MaxPathLength string `json:"maxPathLength,omitempty"`

	PermittedDNS []string `json:"permittedDNS,omitempty"`

	ExcludedDNS []string `json:"excludedDNS,omitempty"`

	PermittedIP []string `json:"permittedIP,omitempty"`

	ExcludedIP []string `json:"excludedIP,omitempty"`

	PermittedEmail []string `json:"permittedEmail,omitempty"`

	ExcludedEmail []string `json:"excludedEmail,omitempty"`

	PermittedURL []string `json:"permittedURL,omitempty"`

	ExcludedURL []string `json:"excludedURL,omitempty"`

	PolicyIdentifiers []string `json:"policyIdentifiers"`
}
