/*
 * CyberArk PKIaaS API
 *
 * API for CyberArk's Public-Key Infrastructure (PKI)-as-a-Service
 *
 * API version: 1.0.2
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse201 struct {

	CommonName string `json:"commonName,omitempty"`

	TemplateName string `json:"templateName,omitempty"`

	TimeToLive int32 `json:"timeToLive,omitempty"`

	ReturnFormat string `json:"returnFormat,omitempty"`
}
