/*
 * CyberArk Identity Service API
 *
 * API for CyberArk's Identity Service
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2006Records struct {

	SerialNumber string `json:"serialNumber,omitempty"`

	RevocationDate string `json:"revocationDate,omitempty"`

	Extensions []InlineResponse2006Extensions `json:"extensions,omitempty"`
}
