/*
 * CyberArk PKIaaS API
 *
 * API for CyberArk's Public-Key Infrastructure (PKI)-as-a-Service
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SshcertificatecreateCriticalOptions struct {

	Option string `json:"option,omitempty"`

	Value string `json:"value,omitempty"`
}
