/*
 * CyberArk Identity Service API
 *
 * API for CyberArk's Identity Service
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body1 struct {

	CommonName string `json:"commonName,omitempty"`

	TemplateName string `json:"templateName,omitempty"`

	Ttl int32 `json:"ttl,omitempty"`

	AltNames []string `json:"altNames,omitempty"`

	ReturnFormat string `json:"returnFormat,omitempty"`
}
