/*
 * CyberArk Identity as a Service API
 *
 * API for CyberArk's Identity as a Service (IDaaS)
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body4 struct {

	TemplateName string `json:"templateName,omitempty"`

	PublicKey string `json:"publicKey,omitempty"`

	Users []string `json:"users,omitempty"`

	Domains []string `json:"domains,omitempty"`

	Ttl int32 `json:"ttl,omitempty"`

	KeyId string `json:"keyId,omitempty"`

	CriticalOptions []SshcertificatecreateCriticalOptions `json:"criticalOptions,omitempty"`

	Extensions []string `json:"extensions,omitempty"`
}
