/*
 * CyberArk Identity Service API
 *
 * API for CyberArk's Identity Service
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PkiTemplateRequest struct {

	TemplateName string `json:"templateName"`

	KeyAlgo string `json:"keyAlgo"`

	KeyBits string `json:"keyBits"`

	MaxTTL int32 `json:"maxTTL"`

	Subject []CagenerateSubject `json:"subject"`

	StoreCertificate bool `json:"storeCertificate"`

	KeyUsages []string `json:"keyUsages,omitempty"`

	ExtKeyUsages []string `json:"extKeyUsages,omitempty"`

	ValidateCNHostname bool `json:"validateCNHostname,omitempty"`

	PermitLocalhostCN bool `json:"permitLocalhostCN,omitempty"`

	PermitWildcardCN bool `json:"permitWildcardCN,omitempty"`

	PermitRootDomain bool `json:"permitRootDomain,omitempty"`

	PermitSubdomainCN bool `json:"permitSubdomainCN,omitempty"`

	AllowedCNDomains []string `json:"allowedCNDomains,omitempty"`

	PermDNSDomains []string `json:"permDNSDomains,omitempty"`

	ExclDNSDomains []string `json:"exclDNSDomains,omitempty"`

	PermIPRanges []string `json:"permIPRanges,omitempty"`

	ExclIPRanges []string `json:"exclIPRanges,omitempty"`

	PermEmails []string `json:"permEmails,omitempty"`

	ExclEmails []string `json:"exclEmails,omitempty"`

	PermURIDomains []string `json:"permURIDomains,omitempty"`

	ExclURIDomains []string `json:"exclURIDomains,omitempty"`

	PolicyIdentifiers []string `json:"policyIdentifiers,omitempty"`
}
