/*
 * CyberArk Identity as a Service API
 *
 * API for CyberArk's Identity as a Service (IDaaS)
 *
 * API version: 1.0.4
 * Contact: joe.garcia@cyberark.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2006 struct {

	Count string `json:"count,omitempty"`

	Records []InlineResponse2006Records `json:"records,omitempty"`
}
